
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cambridgelc
    username: postgres
    password: 1125
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
